name: Price Scraper

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:


jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install Playwright
        run: pip install playwright
      - name: Install Playwright dependencies (Ubuntu)
        run: |
          npx playwright install-deps
      - name: Install Playwright browsers
        run: python -m playwright install
      - name: Run scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python src/main.py
      - name: Commit price history
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A  # Stage all changes
          git diff --cached --quiet || git commit -m "Update price history"
          git pull --rebase
          git push
