name: Push output.html to Google Cloud Storage

on:
  push:
    branches:
      - master
    paths:
      - output.html
  workflow_dispatch:

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check output.html is non-empty and valid
        id: check_output
        run: |
          if [ ! -s output.html ]; then
            echo "output.html is empty. Skipping upload."
            exit 1
          fi
          if ! grep -q '<title>' output.html; then
            echo "output.html missing <title> tag."
            exit 1
          fi
          if ! grep -qi '<body' output.html; then
            echo "output.html missing <body> tag."
            exit 1
          fi
          if ! grep -q '<ul' output.html; then
            echo "output.html missing <ul> tag."
            exit 1
          fi

      - name: Set up authentication
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCS_BUCKET_SVC_ACCOUNT_JSON_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2.1.5
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Upload output.html to GCS bucket
        run: |
          gsutil cp output.html gs://${{ secrets.GCS_BUCKET_NAME_NEWPC }}/output.html
